const mongoose=require("mongoose")
const userDetails=mongoose.Schema({
    Branch:{
        type:String
     
    },
    studentFirstName:{
        type:String
     
    },
    studentLastName:{
        type:String
    },
    gender:{
        type:String,
        enum:["Male","Female","others"]
    },
    addmissionYear:{
      type:Number
    },
    studentclass:{
        type:String,
        enum:["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th","Intermediate","Degree"]
      },
      DateOfBirth:{
        type:Date
      },
      secondLanguage:{
        type:String,
        enum:["Hindi","Telugu","French"]
      },
      thirdLanguage:{
        type:String,
        enum:["Spanish","German"]
      },
      guardianFirstName:{
        type:String
      },
      guardianLastName:{
        type:String
      },
      mobileNo:{
        type:Number
      },
      emailId:{
        type:String
      },
      relationShip:{
        type:String,
        enum:["Father","Mother","Uncle","Aunty","Sister","Brother"]
      },
      pincode:{
        type:Number
      },
      State:{
        type:String
      },
      District:{
        type:String
      },
      address1:{
        type:String
      },
      address2:{
        type:String
      },
      campusTour:{
        type:String
      },
      hearAboutUs:{
        type:String,
        enum:["LinkedIn","Facebook","Naukari","Indeed","Whatsapp"]
      },
      AddInfo:{
        type:String
      }
},{timestamps:true})
module.exports=mongoose.model("userdetails",userDetails)